version: "3.9"

services:
  app:
    build:
      context: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
